# Generated by Django 3.2 on 2021-04-13 03:17

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('categories', models.CharField(choices=[('not selected', 'not selected'), ('Electronics', 'Elecronics'), ('Furniture', 'Furniture'), ('Apartment', 'Apartment'), ('Other stuffs', 'Other stuffs')], default='not selected', max_length=30)),
                ('sold', models.BooleanField(default=False)),
                ('descriptions', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_two', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('image_three', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
            ],
        ),
    ]
