# Generated by Django 3.1.3 on 2021-04-27 04:26

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('categories', models.CharField(choices=[('not selected', 'not selected'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Apartment', 'Apartment'), ('Other stuffs', 'Other stuffs')], default='not selected', max_length=30)),
                ('sold', models.BooleanField(blank=True, default=False)),
                ('contact_number', models.CharField(blank=True, default='no number', max_length=13)),
                ('descriptions', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_two', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('image_three', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
