# Generated by Django 3.1.3 on 2021-05-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markethub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Other stuffs', 'Other stuffs'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Apartment', 'Apartment'), ('Gadgets', 'Gadgets'), ('Female Boutique', 'Female Boutique'), ('Male Boutique', 'Male Boutique')], default='not selected', max_length=30),
        ),
    ]
