# Generated by Django 3.1.3 on 2021-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markethub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
