# Generated by Django 3.1.3 on 2021-04-24 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markethub', '0002_auto_20210416_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_number',
            field=models.CharField(blank=True, default='no number', max_length=13),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('not selected', 'not selected'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Apartment', 'Apartment'), ('Other stuffs', 'Other stuffs')], default='not selected', max_length=30),
        ),
    ]
