# Generated by Django 3.1.3 on 2021-05-01 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
