# Generated by Django 3.1.3 on 2021-04-24 06:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_corper_blog_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corper_blog',
            name='post_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
