# Generated by Django 3.1.3 on 2021-05-01 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='myuser',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
