# Generated by Django 3.1.3 on 2021-04-27 05:44

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('not selected', 'not selected'), ('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('Realtor', 'Realtor'), ('Software-developer', 'Software-developer'), ('Personal-Shopper', 'Personal-Shopper'), ('beautician', 'beautician'), ('Hair-dresser', 'Hair-dresser'), ('Barber', 'Barber'), ('Fashion-designer', 'Fashion-designer'), ('Painter', 'Painter'), ('Photographer', 'Photographer'), ('Baker', 'Baker')], default='not selected', max_length=30)),
                ('descriptions', models.TextField(max_length=200)),
                ('contact_number', models.CharField(max_length=13)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_two', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('image_three', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
